project_id = "pqindxqwxysvenzwxyjp"

[functions.crear-version]
verify_jwt = false

[functions.analizar-comentarios]
verify_jwt = false

[functions.analisis-version]
verify_jwt = false

[functions.analisis-filtrado-chunk]
verify_jwt = false

[functions.create-public-dashboard-link]
verify_jwt = false

